let navMap = {
  "store.usr_login": "/fe/app11/web/login.js",

  "store.activity_lst": "/app11/fe/mod01/web/activity/activity_lst.js",
  "store.activity_dtl": "/app11/fe/mod01/web/activity/activity_dtl.js",
  "store.staff_lst": "/app11/fe/mod01/web/staff/staff_lst.js",
  "store.staff_dtl": "/app11/fe/mod01/web/staff/staff_dtl.js",
  "store.location_lst": "/fe/app11/mod01/web/location/location_lst.js",
  "store.location_dtl": "/app11/fe/mod01/web/location/location_dtl.js",
  "store.farmer_lst": "/app11/fe/mod01/web/view/farmer_lst.js",
  "store.farmer_dtl": "/app11/fe/mod01/web/view/farmer_dtl.js",
  "store.cattle_lst": "/app11/fe/mod01/web/view/cattle_lst.js",
  "store.cattle_dtl": "/app11/fe/mod01/web/view/cattle_dtl.js",
  "store.request_lst": "/app11/fe/mod01/web/view/request_lst.js",
  "store.request_dtl": "/app11/fe/mod01/web/view/request_dtl.js",
  "store.followup_lst": "/app11/fe/mod01/web/view/followup_lst.js",
  "store.followup_dtl": "/app11/fe/mod01/web/view/followup_dtl.js",
  "store.visit_lst": "/app11/fe/mod01/web/view/visit_lst.js",
  "store.visit_dtl": "/app11/fe/mod01/web/view/visit_dtl.js",
  "store.hospital_lst": "/app11/fe/mod01/web/hospital/hospital_lst.js",
  "store.hospital_dtl": "/app11/fe/mod01/web/hospital/hospital_dtl.js",
  
  "store.metric_lst": "/app11/fe/mod01/web/metric/metric_lst.js",
  "store.metric_dtl": "/app11/fe/mod01/web/metric/metric_dtl.js",
  "store.activityreport_lst": "/app11/fe/mod01/web/activityreport/activityreport_lst.js",
  "store.summary_lst": "/app11/fe/mod01/web/summaryreport/summary_lst.js",
  "store.aidetailreport_lst": "/app11/fe/mod01/web/aidetailreport/aidetailreport_lst.js",
  "store.projectreport_lst": "/app11/fe/mod01/web/projectreport/projectreport_lst.js",
  
  "mob.farmer_lst": "/app11/fe/mod02/mob/farmer_lst.js",
  "mob.farmer_dtl": "/app11/fe/mod02/mob/farmer_dtl.js",
  "mob.request_lst": "/app11/fe/mod02/mob/request_lst.js",
  "mob.request_dtl": "/app11/fe/mod02/mob/request_dtl.js",
  "mob.cattle_lst": "/app11/fe/mod02/mob/cattle_lst.js",
  "mob.cattle_dtl": "/app11/fe/mod02/mob/cattle_dtl.js",
  "mob.visit_lst": "/app11/fe/mod02/mob/visit_lst.js",
  "mob.visit_dtl": "/app11/fe/mod02/mob/visit_dtl.js",
  "mob.followup_lst": "/app11/fe/mod02/mob/followup_lst.js",
  "mob.followup_dtl": "/app11/fe/mod02/mob/followup_dtl.js"
  
}
